name: Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout code
      uses: actions/checkout@v3
    -
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    -
      name: Build docker images
      run: docker-compose build
    -
      name: Install dependencies
      uses: bahmutov/npm-install@v1
    -
      name: Run tests
      run: docker-compose run test
      